run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: false
  go: '1.23'

linters:
  enable:
    - revive
    - exportability
    - unused
    - errcheck
    - errorlint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - whitespace

output:
  format: line-number
  print-issued-lines: false
  print-linter-name: true
  sort-results: true

# all available settings of specific linters
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - commentFormatting
      - hugeParam     # does not work with generics
      - typeDefFirst     # does not work with generics
      - whyNoLint

  gocyclo:
    min-complexity: 20

  goimports:
    local-prefixes: diianpro/coin-merch-store

  gci:
    sections:
      - standard                                  # Standard section: captures all standard packages.
      - default                                   # Default section: contains all imports that could not be matched to another section type.
      - prefix(diianpro/coin-merch-store)         # Custom section: groups all imports with the specified Prefix.
      - blank                                     # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot                                       # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
    skip-generated: true
    custom-order: true

  gofumpt:
    lang-version: '1.23'
    extra-rules: true
