version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - /pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d image -U su" ]
      interval: 5s
      timeout: 1s
      retries: 2
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data:
